### ISSUE TITLE
covid-solver-windows V1.3 Error docking package

### ISSUE THREAD

**Issue by utraun** [pevecyan/covid-solver-windows#1]
Prerequired files downloaded
Calculating package 4051
333 2
lib\rxdock\builddir-win64\rbdock.exe -r target\TARGET_1.prm -p dock.prm -f \target\htvs.ptc -i package\package_2.sdf -o package\package_2_out
lib\rxdock\builddir-win64\rbdock.exe -r target\TARGET_1.prm -p dock.prm -f \target\htvs.ptc -i package\package_0.sdf -o package\package_0_out
lib\rxdock\builddir-win64\rbdock.exe -r target\TARGET_1.prm -p dock.prm -f \target\htvs.ptc -i package\package_1.sdf -o package\package_1_out
Error docking package (stdout) 0 : 3221225781
Error docking package (stdout) 2 : 3221225781
Error docking package (stdout) 1 : 3221225781
Package done calculating
Done calculating page
File uploaded page
[log.zip](https://github.com/pevecyan/covid-solver-windows/files/4424590/log.zip)

**Comment by pevecyan** [comment]
@utraun  strange, logs are empty. Can you maybe run rbdock.exe manually from command line. By exit code it looks like some kind of library is missing.

**Comment by pevecyan** [comment]
This should be resolved by latest version. Closing thins issue now.
