### ISSUE TITLE
Shorter timeout in case there are no targets available

### ISSUE THREAD

**Issue by DrRogla** [pevecyan/covid-solver-windows#4]
https://github.com/pevecyan/covid-solver-windows/blob/9edf6b013bd6227dcd3106bd51d4cfe860c19b97/main.go#L210-214

I am getting the no new targets message, but restarting gets new data with no problem.
It might be more to do with network traffic.

So this delay could be shorter, e.g. 2-5min, to get more packages done.

**Comment by pevecyan** [comment]
Good idea, you can create pull request with fix and I will publish new release later.

**Comment by DrRogla** [comment]
Done! 
Recommend shortening to 3 minutes. 
It takes less time than that on my box to process one set of packages.

**Comment by DrRogla** [comment]
Fixed in V1.9.
